# Generated by Django 4.0.3 on 2022-05-17 10:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('id', models.BigAutoField(db_column='fld_ai_id', primary_key=True, serialize=False)),
                ('email', models.EmailField(max_length=100, unique=True, verbose_name='Email')),
                ('phone', models.CharField(max_length=100, unique=True)),
                ('user_level', models.IntegerField(blank=True, null=True)),
                ('user_id', models.CharField(blank=True, max_length=100, null=True)),
                ('is_active', models.BooleanField(db_column='fld_is_active', default=True)),
                ('is_admin', models.BooleanField(db_column='fld_is_admin', default=False)),
            ],
            options={
                'db_table': 'tbl_users',
            },
        ),
    ]
