# Generated by Django 4.0.3 on 2022-05-27 21:38

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblUserReimbursements',
            fields=[
                ('id', models.AutoField(db_column='fld_ai_id', primary_key=True, serialize=False)),
                ('claim_id', models.CharField(blank=True, db_column='fld_claim_id', max_length=100, null=True)),
                ('distance', models.IntegerField(blank=True, db_column='fld_distance', null=True)),
                ('amount', models.IntegerField(blank=True, db_column='fld_amount', null=True)),
                ('status', models.CharField(blank=True, choices=[('completed', 'completed'), ('pending', 'pending')], db_column='fld_status', max_length=20, null=True)),
                ('is_active', models.BooleanField(db_column='fld_is_active', default=True)),
                ('is_delete', models.BooleanField(db_column='fld_is_delete', default=False)),
                ('date', models.DateField(blank=True, db_column='fld_date', null=True)),
                ('created_datetime', models.DateTimeField(blank=True, db_column='fld_created_datetime', null=True)),
                ('user_id', models.ForeignKey(blank=True, db_column='fld_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_user_reimbursements',
            },
        ),
    ]
