# Generated by Django 4.0.3 on 2022-05-27 22:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0002_tbluserreimbursements'),
    ]

    operations = [
        migrations.AddField(
            model_name='tbluserreimbursements',
            name='visit_id',
            field=models.CharField(blank=True, db_column='fld_visit_id', max_length=50, null=True),
        ),
    ]
