# Generated by Django 4.0.3 on 2022-05-27 23:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0003_tbluserreimbursements_visit_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbluserreimbursements',
            name='status',
            field=models.CharField(blank=True, choices=[('completed', 'completed'), ('pending', 'pending')], db_column='fld_status', default='pending', max_length=20, null=True),
        ),
    ]
