# Generated by Django 4.0.3 on 2022-05-28 11:04

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('database', '0004_alter_tbluserreimbursements_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='TblAttendanceLog',
            fields=[
                ('id', models.AutoField(db_column='fld_ai_id', primary_key=True, serialize=False)),
                ('claim_id', models.CharField(blank=True, db_column='fld_claim_id', max_length=100, null=True)),
                ('visit_id', models.CharField(blank=True, db_column='fld_visit_id', max_length=50, null=True)),
                ('site_id', models.CharField(blank=True, db_column='fld_site_omc_id', max_length=10, null=True)),
                ('site_name', models.CharField(blank=True, db_column='fld_site_name', max_length=100, null=True)),
                ('distance', models.IntegerField(blank=True, db_column='fld_distance', null=True)),
                ('amount', models.IntegerField(blank=True, db_column='fld_amount', null=True)),
                ('check_in_time', models.TimeField(blank=True, db_column='fld_check_in_time', null=True)),
                ('check_out_time', models.TimeField(blank=True, db_column='fld_check_out_time', null=True)),
                ('date', models.DateField(blank=True, db_column='fld_date', null=True)),
                ('is_active', models.BooleanField(db_column='fld_is_active', default=True)),
                ('is_delete', models.BooleanField(db_column='fld_is_delete', default=False)),
                ('created_datetime', models.DateTimeField(blank=True, db_column='fld_created_datetime', null=True)),
                ('user_id', models.ForeignKey(blank=True, db_column='fld_user_id', null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'tbl_attendance_log',
            },
        ),
    ]
