# Generated by Django 4.0.3 on 2022-05-28 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0006_remove_tblattendancelog_amount_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblattendancelog',
            name='distance',
            field=models.FloatField(blank=True, db_column='fld_distance', null=True),
        ),
    ]
