# Generated by Django 4.0.3 on 2022-05-28 23:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0007_alter_tblattendancelog_distance'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tblattendancelog',
            name='site_id',
            field=models.CharField(blank=True, db_column='fld_site_omc_id', max_length=100, null=True),
        ),
    ]
