# Generated by Django 4.0.3 on 2022-05-29 15:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0008_alter_tblattendancelog_site_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='tblattendance',
            name='visit_id',
            field=models.CharField(blank=True, db_column='fld_visit_id', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='tblattendancelog',
            name='visit_id',
            field=models.CharField(blank=True, db_column='fld_visit_id', max_length=50, null=True),
        ),
    ]
