# Generated by Django 4.0.3 on 2022-06-01 15:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('database', '0011_tbluserreimbursements2_tblattendancelog2'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tbluserreimbursements',
            name='status',
            field=models.CharField(blank=True, choices=[('approved', 'approved'), ('pending', 'pending'), ('requested', 'requested'), ('closed', 'closed')], db_column='fld_status', default='pending', max_length=20, null=True),
        ),
        migrations.DeleteModel(
            name='TblUserReimbursements2',
        ),
    ]
